### ISSUE TITLE
Duplicate Connection Via AMQP_WS Segfaults

### ISSUE THREAD

**Issue by ling0015** [Azure/azure-iot-sdk-c#1374]
I recently had a test machine go rogue and it was running tests in parallel that should not be. This was resulting in segmentation faults. 

I was able to reproduce this issue by using the attached patch file on the sample iothub_client_device_twin_and_methods_sample.c. I then just started two instances at the same time, they both fight over the connection and will flip between authenticated and unauthenticated with no genuine data transfer occurring, and a ~5 minutes later one of them crashed.

This behavior is noted in 1.3.7 and 1.3.6, however, on 1.3.3 one of the programs seems to "win" and owns the connection while the other remains disconnected, and no segmentation fault is observed.

The stack trace is very similar to the stack trace in https://github.com/Azure/azure-iot-sdk-c/issues/1089.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
$ git rev-parse HEAD
509228d0641878a714b91771aae9c3990808079f
$ cmake -Dbuild_as_dynamic:BOOL=ON -Duse_amqp=ON ../
-- IoT Client SDK Version = 1.3.7
-- target architecture: x86_64
-- target architecture: x86_64
-- iothub architecture: x86_64
-- Configuring done
-- Generating done
-- Build files have been written to: /home/Downloads/azure-iot-sdk-c/cmake
```
**Backtrace**
```
connection status result: IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED

connection status reason: IOTHUB_CLIENT_CONNECTION_OK

connection status result: IOTHUB_CLIENT_CONNECTION_AUTHENTICATED

connection status reason: IOTHUB_CLIENT_CONNECTION_OK
Error: Time:Mon Dec 16 14:50:17 2019 File:/home/Downloads/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_twin_messenger.c Func:on_amqp_messenger_subscription_changed_callback Line:1677 Unexpected AMQP messenger state (tartan_test_fixture, TWIN_MESSENGER_STATE_STARTED, 0)
Error: Time:Mon Dec 16 14:50:17 2019 File:/home/Downloads/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_twin_messenger.c Func:on_amqp_send_complete_callback Line:934 Failed sending TWIN operation request (tartan_test_fixture, TWIN_OPERATION_TYPE_PUT, 12fca6b2-bcc2-479c-b896-8758a6e71a1f, AMQP_MESSENGER_SEND_RESULT_ERROR, AMQP_MESSENGER_REASON_FAIL_SENDING)
Error: Time:Mon Dec 16 14:50:17 2019 File:/home/Downloads/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_device.c Func:amqp_device_do_work Line:1103 Device 'tartan_test_fixture' is started but TWIN messenger reported unexpected state 4

connection status result: IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED

connection status reason: IOTHUB_CLIENT_CONNECTION_COMMUNICATION_ERROR
Error: Time:Mon Dec 16 14:50:17 2019 File:/home/Downloads/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:1150 Failed performing DoWork for device 'tartan_test_fixture' (device reported state 6; number of previous failures: 0)

connection status result: IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED

connection status reason: IOTHUB_CLIENT_CONNECTION_OK

Thread 2 "iothub_client_d" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff1c3b700 (LWP 31075)]
0x00007ffff7b3cf6b in on_session_flow_on ()
   from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
(gdb) bt
#0  0x00007ffff7b3cf6b in on_session_flow_on () from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
#1  0x00007ffff7b49f6e in on_frame_received () from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
#2  0x00007ffff7b37e25 in on_amqp_frame_received () from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
#3  0x00007ffff7b4b850 in frame_received () from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
#4  0x00007ffff7b3abe7 in frame_codec_receive_bytes () from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
#5  0x00007ffff7b36de1 in connection_byte_received () from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
#6  0x00007ffff7b36e98 in connection_on_bytes_received () from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
#7  0x00007ffff7b47179 in on_underlying_io_bytes_received () from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
#8  0x00007ffff7b76ecb in on_underlying_ws_frame_received () from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
#9  0x00007ffff7b7ab67 in on_underlying_io_bytes_received () from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
#10 0x00007ffff7b74210 in decode_ssl_received_bytes () from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
#11 0x00007ffff7b742cd in on_underlying_io_bytes_received () from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
#12 0x00007ffff7b7f6ad in socketio_dowork () from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
#13 0x00007ffff7b6109e in xio_dowork () from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
#14 0x00007ffff7b754d7 in tlsio_openssl_dowork () from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
#15 0x00007ffff7b6109e in xio_dowork () from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
#16 0x00007ffff7b7bf83 in uws_client_dowork () from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
#17 0x00007ffff7b775e0 in wsio_dowork () from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
#18 0x00007ffff7b6109e in xio_dowork () from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
#19 0x00007ffff7b48c6e in saslclientio_dowork () from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
#20 0x00007ffff7b6109e in xio_dowork () from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
#21 0x00007ffff7b39781 in connection_dowork () from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
#22 0x00007ffff7af01f1 in amqp_connection_do_work () from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
#23 0x00007ffff7ae72c9 in IoTHubTransport_AMQP_Common_DoWork () from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
#24 0x00007ffff7b065dc in IoTHubTransportAMQP_WS_DoWork () from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
#25 0x00000000004114fe in IoTHubClientCore_LL_DoWork ()
#26 0x0000000000408804 in ScheduleWork_Thread ()
#27 0x00007ffff7b6a11e in ThreadWrapper () from /home/Downloads/azure-iot-sdk-c/cmake/iothub_client/libiothub_client.so.1
#28 0x00007ffff68986ba in start_thread (arg=0x7ffff1c3b700) at pthread_create.c:333
#29 0x00007ffff74d241d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) 
```

**Comment by ling0015** [comment]
Attaching patch file.

[segfault.txt](https://github.com/Azure/azure-iot-sdk-c/files/3970165/segfault.txt)

**Comment by ewertons** [comment]
Hi @ling0015 ,
thanks for sharing the traces.

However, are you using the same connection string (same device-id actually) in more than one iothub client at the same time?

**Comment by ling0015** [comment]
That is correct.

**Comment by ewertons** [comment]
@ling0015 , 
apologies for the long delay on replying, but we were reassigned to work on new development and that impacted on the github issue response time.

A connection string (more specifically, a device ID or module ID) can only be used once per connection with the Azure IoT Hub at any given time. If you need to have more than one connection at a time, please create another device with a different ID to use on the other endpoint.

We will close this issue since it has been stale for quite some time and the response above is pretty conclusive. However, please feel free to reopen it if you would like to follow up.

Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@ling0015, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
