### ISSUE TITLE
IoTHubModuleClient_SetStreamRequestCallback subscribe failed in IoT Edge Module

### ISSUE THREAD

**Issue by v-jiacz** [Azure/azure-iot-sdk-c#1514]
**How to add stream features in IoT Edge Device Module?**

After set IoTHubModuleClient_SetStreamRequestCallback function, the callback received nothing and the azureiotedge-hub log as follows:

**azureiotedge-hub:1.0 log show "Ignoring unknown subscription to topic $iothub/streams/POST/# for client"**

```
PS F:\SantaCruze\EVT\Modules\SpeechModule-CareyTest> docker logs -f 4c456266b1bc47127742d5860ad0a0c8c36f34a8ff9717bfc56b17f89d389576
2020-04-22 06:35:56  Starting Edge Hub
2020-04-22 06:35:57.537 +00:00 Edge Hub Main()
<6> 2020-04-22 06:35:58.285 +00:00 [INF] - Installing certificates [CN=Edge Agent CA, OU=Default Edge Organization, O=Default Edge Organization, L=Redmond, S=Washington, C=US:04/20/2021 02:56:27],[CN=Edge Test Device CA, OU=Default Edge Organization, O=Default Edge Organization, L=Redmond, S=Washington, C=US:04/21/2021 02:56:24] to Root
<6> 2020-04-22 06:35:58.333 +00:00 [INF] - Installing certificates  to Root
<6> 2020-04-22 06:36:00.852 +00:00 [INF] - Created persistent store at /tmp/edgeHub
<6> 2020-04-22 06:36:00.879 +00:00 [INF] - Created device scope identities cache
<6> 2020-04-22 06:36:00.884 +00:00 [INF] - Initializing Edge Hub
<6> 2020-04-22 06:36:00.885 +00:00 [INF] - 
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2020-04-22 06:36:00.888 +00:00 [INF] - Version - 1.0.9.29532150 (1f7cf6a21dfa365c8f21475553c544f4df02dd44)
<6> 2020-04-22 06:36:00.888 +00:00 [INF] - OptimizeForPerformance=True
<6> 2020-04-22 06:36:00.893 +00:00 [INF] - Starting refresh of device scope identities cache
<6> 2020-04-22 06:36:00.896 +00:00 [INF] - Loaded server certificate with expiration date of "2021-04-19T02:56:27.0000000+00:00"
<6> 2020-04-22 06:36:00.972 +00:00 [INF] - Created new message store
<6> 2020-04-22 06:36:00.972 +00:00 [INF] - Started task to cleanup processed and stale messages
<6> 2020-04-22 06:36:01.171 +00:00 [INF] - Created DeviceConnectivityManager with connected check frequency 00:05:00 and disconnected check frequency 00:02:00
<6> 2020-04-22 06:36:01.364 +00:00 [INF] - Initialized storing twin manager
<6> 2020-04-22 06:36:01.387 +00:00 [INF] - Initializing configuration
<6> 2020-04-22 06:36:01.627 +00:00 [INF] - Created cloud endpoint iothub with max batch size 10 and fan-out factor of 10.
<4> 2020-04-22 06:36:01.649 +00:00 [WRN] - Empty edge hub configuration received. Ignoring...
<6> 2020-04-22 06:36:02.050 +00:00 [INF] - Set the following 2 route(s) in edge hub
<6> 2020-04-22 06:36:02.051 +00:00 [INF] - r1: FROM /messages/modules/SpeechBotClient/outputs/* INTO $upstream
<6> 2020-04-22 06:36:02.051 +00:00 [INF] - r2: FROM /messages/modules/SimulatedTemperatureSensor/outputs/temperatureOutput INTO BrokeredEndpoint("/modules/SpeechBotClient/inputs/input1")
<6> 2020-04-22 06:36:02.054 +00:00 [INF] - Updated message store TTL to -1 seconds
<6> 2020-04-22 06:36:02.054 +00:00 [INF] - Updated the edge hub store and forward configuration
<6> 2020-04-22 06:36:02.071 +00:00 [INF] - Started operation Get EdgeHub config
<6> 2020-04-22 06:36:02.072 +00:00 [INF] - Initialized edge hub configuration
<6> 2020-04-22 06:36:02.094 +00:00 [INF] - Starting timer to authenticate connections with a period of 300 seconds
<6> 2020-04-22 06:36:02.376 +00:00 [INF] - Scheduling server certificate renewal for "2021-04-19T02:53:57.0000969Z".
<6> 2020-04-22 06:36:02.379 +00:00 [INF] - Starting protocol heads - (MQTT, AMQP, HTTP)
<6> 2020-04-22 06:36:02.384 +00:00 [INF] - Starting MQTT head
<6> 2020-04-22 06:36:02.430 +00:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
<6> 2020-04-22 06:36:02.506 +00:00 [INF] - Starting AMQP head
<6> 2020-04-22 06:36:02.546 +00:00 [INF] - Started MQTT head
<6> 2020-04-22 06:36:02.619 +00:00 [INF] - Started AMQP head
<6> 2020-04-22 06:36:02.623 +00:00 [INF] - Starting HTTP head
<6> 2020-04-22 06:36:02.623 +00:00 [INF] - Starting HTTP head
<6> 2020-04-22 06:36:02.794 +00:00 [INF] - User profile is available. Using '"/home/edgehubuser/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest.
<6> 2020-04-22 06:36:02.826 +00:00 [INF] - Creating key {a93ac5d2-74da-4cfd-82b6-1d2e6b92f70e} with creation date 2020-04-22 06:36:02Z, activation date 2020-04-22 06:36:02Z, and expiration date 2020-07-21 06:36:02Z.    
<4> 2020-04-22 06:36:02.853 +00:00 [WRN] - No XML encryptor configured. Key {a93ac5d2-74da-4cfd-82b6-1d2e6b92f70e} may be persisted to storage in unencrypted form.
<6> 2020-04-22 06:36:02.859 +00:00 [INF] - Writing data to file '"/home/edgehubuser/.aspnet/DataProtection-Keys/key-a93ac5d2-74da-4cfd-82b6-1d2e6b92f70e.xml"'.
<4> 2020-04-22 06:36:03.390 +00:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
<6> 2020-04-22 06:36:03.440 +00:00 [INF] - Started HTTP head
<6> 2020-04-22 06:36:06.464 +00:00 [INF] - Client carey_edge_888/SpeechBotClient in device scope authenticated locally.                                                                                                    preview&DeviceClientType=
<6> 2020-04-22 06:36:06.501 +00:00 [INF] - Successfully generated identity for clientId carey_edge_888/SpeechBotClient and username peszihvhubpnp.azure-devices.net/carey_edge_888/SpeechBotClient/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.3.1%20(native%3b%20Linux%3b%20armv7l)
<6> 2020-04-22 06:36:06.507 +00:00 [INF] - ClientAuthenticated, carey_edge_888/SpeechBotClient, 7184cdbd
<6> 2020-04-22 06:36:06.568 +00:00 [INF] - New device connection for device carey_edge_888/SpeechBotClient
<6> 2020-04-22 06:36:06.569 +00:00 [INF] - Bind device proxy for device carey_edge_888/SpeechBotClient
<6> 2020-04-22 06:36:06.570 +00:00 [INF] - Binding message channel for device Id carey_edge_888/SpeechBotClient
<6> 2020-04-22 06:36:06.604 +00:00 [INF] - Ignoring unknown subscription to topic $iothub/streams/POST/# for client carey_edge_888/SpeechBotClient.
<6> 2020-04-22 06:36:06.604 +00:00 [INF] - Ignoring unknown subscription to topic $iothub/streams/res/# for client carey_edge_888/SpeechBotClient.
<6> 2020-04-22 06:36:06.610 +00:00 [INF] - Processing subscriptions TwinResponse, Methods, ModuleMessages, Unknown, Unknown for client carey_edge_888/SpeechBotClient.
<6> 2020-04-22 06:36:06.624 +00:00 [INF] - Processing pending subscriptions for carey_edge_888/SpeechBotClient
<6> 2020-04-22 06:36:06.650 +00:00 [INF] - Set subscriptions from session state for carey_edge_888/SpeechBotClient
<6> 2020-04-22 06:36:06.737 +00:00 [INF] - Attempting to connect to IoT Hub for client carey_edge_888/SpeechBotClient via AMQP...
<6> 2020-04-22 06:36:10.496 +00:00 [INF] - Exiting disconnected state
<6> 2020-04-22 06:36:10.501 +00:00 [INF] - Received device connected callback
<6> 2020-04-22 06:36:10.526 +00:00 [INF] - Done syncing reported properties for carey_edge_888/SpeechBotClient
<6> 2020-04-22 06:36:10.547 +00:00 [INF] - Device connected to cloud, processing subscriptions for connected clients.
<6> 2020-04-22 06:36:10.551 +00:00 [INF] - Processing subscriptions for client carey_edge_888/SpeechBotClient on device connected.
<6> 2020-04-22 06:36:10.564 +00:00 [INF] - Starting refresh of device scope identities cache
<6> 2020-04-22 06:36:10.577 +00:00 [INF] - Entering connected state
<6> 2020-04-22 06:36:10.581 +00:00 [INF] - Cloud connection for carey_edge_888/SpeechBotClient is True
<6> 2020-04-22 06:36:10.589 +00:00 [INF] - Connection status for carey_edge_888/SpeechBotClient changed to ConnectionEstablished
<6> 2020-04-22 06:36:10.592 +00:00 [INF] - Client carey_edge_888/SpeechBotClient connected to cloud, processing existing subscriptions.
<6> 2020-04-22 06:36:10.599 +00:00 [INF] - Created cloud proxy for client carey_edge_888/SpeechBotClient via AMQP, with client operation timeout 20 seconds.
<6> 2020-04-22 06:36:10.606 +00:00 [INF] - Initialized cloud proxy 8d279ab1-dfe5-47eb-abf7-628665671729 for carey_edge_888/SpeechBotClient
<6> 2020-04-22 06:36:10.608 +00:00 [INF] - Created cloud connection for client carey_edge_888/SpeechBotClient
<6> 2020-04-22 06:36:11.666 +00:00 [INF] - Ignoring unknown subscription to topic $iothub/streams/POST/# for client carey_edge_888/SpeechBotClient.
<6> 2020-04-22 06:36:11.666 +00:00 [INF] - Ignoring unknown subscription to topic $iothub/streams/res/# for client carey_edge_888/SpeechBotClient.
<6> 2020-04-22 06:36:11.667 +00:00 [INF] - Processing subscriptions TwinResponse, Methods, ModuleMessages, Unknown, Unknown, DesiredPropertyUpdates for client carey_edge_888/SpeechBotClient.
<6> 2020-04-22 06:36:11.667 +00:00 [INF] - Processing pending subscriptions for carey_edge_888/SpeechBotClient
<6> 2020-04-22 06:36:11.748 +00:00 [INF] - Set subscriptions from session state for carey_edge_888/SpeechBotClient
<6> 2020-04-22 06:36:12.247 +00:00 [INF] - Updated reported properties for carey_edge_888/SpeechBotClient
<6> 2020-04-22 06:36:18.037 +00:00 [INF] - Updated reported properties for carey_edge_888/SpeechBotClient
<6> 2020-04-22 06:41:02.100 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-04-22 06:46:02.094 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-04-22 06:51:02.094 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-04-22 06:56:02.095 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-04-22 07:01:02.094 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-04-22 07:06:00.989 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
<6> 2020-04-22 07:06:01.139 +00:00 [INF] - Cleaned up 360 messages from queue for endpoint iothub and 360 messages from message store.
<6> 2020-04-22 07:06:02.094 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-04-22 07:06:31.140 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint carey_edge_888/SpeechBotClient/input1
<6> 2020-04-22 07:06:31.143 +00:00 [INF] - Cleaned up 0 messages from queue for endpoint carey_edge_888/SpeechBotClient/input1 and 0 messages from message store.
<4> 2020-04-22 07:07:01.157 +00:00 [WRN] - Error cleaning up messages in message store
System.ArgumentOutOfRangeException: The value needs to translate in milliseconds to -1 (signifying an infinite timeout), 0 or a positive integer less than or equal to Int32.MaxValue.
Parameter name: delay
   at System.Threading.Tasks.Task.Delay(TimeSpan delay, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore.CleanupProcessor.CleanupMessages() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/storage/MessageStore.cs:line 241
<6> 2020-04-22 07:11:02.095 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-04-22 07:16:02.094 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-04-22 07:21:02.093 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-04-22 07:24:06.797 +00:00 [INF] - Closing connection for device: carey_edge_888/SpeechBotClient, , 
<6> 2020-04-22 07:24:06.799 +00:00 [INF] - Disposing MessagingServiceClient for device Id carey_edge_888/SpeechBotClient because of exception - 
<6> 2020-04-22 07:24:06.804 +00:00 [INF] - Setting device proxy inactive for device Id carey_edge_888/SpeechBotClient
<6> 2020-04-22 07:24:06.813 +00:00 [INF] - Device connection removed for device carey_edge_888/SpeechBotClient
<6> 2020-04-22 07:24:06.814 +00:00 [INF] - Remove device connection for device carey_edge_888/SpeechBotClient
<6> 2020-04-22 07:24:06.897 +00:00 [INF] - Client carey_edge_888/SpeechBotClient in device scope authenticated locally.
<6> 2020-04-22 07:24:06.897 +00:00 [INF] - Successfully generated identity for clientId carey_edge_888/SpeechBotClient and username peszihvhubpnp.azure-devices.net/carey_edge_888/SpeechBotClient/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.3.1%20(native%3b%20Linux%3b%20armv7l)
<6> 2020-04-22 07:24:06.897 +00:00 [INF] - ClientAuthenticated, carey_edge_888/SpeechBotClient, 22a9e527
<6> 2020-04-22 07:24:06.900 +00:00 [INF] - New device connection for device carey_edge_888/SpeechBotClient
<6> 2020-04-22 07:24:06.900 +00:00 [INF] - Bind device proxy for device carey_edge_888/SpeechBotClient
<6> 2020-04-22 07:24:06.900 +00:00 [INF] - Binding message channel for device Id carey_edge_888/SpeechBotClient
<6> 2020-04-22 07:24:06.904 +00:00 [INF] - Ignoring unknown subscription to topic $iothub/streams/POST/# for client carey_edge_888/SpeechBotClient.
<6> 2020-04-22 07:24:06.904 +00:00 [INF] - Ignoring unknown subscription to topic $iothub/streams/res/# for client carey_edge_888/SpeechBotClient.
<6> 2020-04-22 07:24:06.904 +00:00 [INF] - Processing subscriptions TwinResponse, Methods, ModuleMessages, Unknown, Unknown, DesiredPropertyUpdates for client carey_edge_888/SpeechBotClient.
<6> 2020-04-22 07:24:06.904 +00:00 [INF] - Processing pending subscriptions for carey_edge_888/SpeechBotClient
<6> 2020-04-22 07:24:06.905 +00:00 [INF] - Set subscriptions from session state for carey_edge_888/SpeechBotClient
<6> 2020-04-22 07:26:02.094 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
```

**Service side log**

```
GatewayTimeoutError: Error: {"Message":"{\"errorCode\":504101,\"trackingId\":\"19470c200704438aaa3196ada840d023-TimeStamp:04/22/2020 06:39:43\",\"message\":\"Timed out waiting for the response from device.\",\"info\":{\"timeout\":\"00:00:30\"},\"timestampUtc\":\"2020-04-22T06:39:43.430524Z\"}","ExceptionMessage":""}
```

**Comment by ewertons** [comment]
Hi @v-jiacz ,
Device Streaming is a public preview feature of azure-iot-sdk-c, and hasn't been integrated with Azure IoT Edge yet.
Indeed it will only be supported after we reach GA (General Availability) for this feature.
Unfortunately it is not planned for this semester.
Please hold until we reach GA for more details.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@v-jiacz, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by ewertons** [comment]
We are closing this issue since we believe a sufficient answer has been provided, however please feel free to reopen it if you would like to follow up.
