### ISSUE TITLE
Identity Manager Error when a new deployment is pushed on edgeAgent

### ISSUE THREAD

**Issue by asm356** [Azure/azure-iot-sdk-c#604]
- **OS and version used:** <VERSION> 

- **SDK version used:** <VERSION> 

Linux Debian 8

# Description of the issue:

Uploaded a new deployment through vs code and the edgeAgent is giving identity management errors and hence not able to get the deployment.

# Code sample exhibiting the issue:

# Console log of the issue:

2018-08-20 21:58:13.344 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
2018-08-20 21:58:13.405 +00:00 [INF] - Obtained edge agent config from backup config file - backup.json
2018-08-20 21:58:30.396 +00:00 [WRN] - Error calling List identities: Identity manager error
        caused by: IoT Hub service error
        caused by: Core error
        caused by: Hyper error
        caused by: failed to lookup address information: Name or service not known
2018-08-20 21:58:30.421 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via AMQP...
2018-08-20 21:58:40.401 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
2018-08-20 21:58:41.461 +00:00 [INF] - Obtained edge agent config from backup config file - backup.json
2018-08-20 21:59:00.452 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via AMQP over WebSocket...
2018-08-20 21:59:00.641 +00:00 [WRN] - Error calling List identities: Identity manager error
        caused by: IoT Hub service error
        caused by: Core error
        caused by: Hyper error
        caused by: failed to lookup address information: Name or service not known
2018-08-20 21:59:10.651 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
2018-08-20 21:59:10.762 +00:00 [INF] - Obtained edge agent config from backup config file - backup.json
2018-08-20 21:59:28.638 +00:00 [WRN] - Error calling List identities: Identity manager error
        caused by: IoT Hub service error
        caused by: Core error
        caused by: Hyper error
        caused by: failed to lookup address information: Name or service not known
2018-08-20 21:59:30.498 +00:00 [WRN] - Error creating a device-to-cloud connection
System.AggregateException: One or more errors occurred. (Operation timeout expired.) (Operation timeout expired.) ---> System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClient.OpenAsync(ConnectionStatusChangesHandler statusChangedHandler, ModuleClient deviceClient) in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClient.cs:line 112
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClient.CreateAndOpenDeviceClient(TransportType transport, Option`1 connectionString, ConnectionStatusChangesHandler statusChangedHandler, Option`1 productInfo) in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClient.cs:line 101
   at Microsoft.Azure.Devices.Edge.Util.Fallback.ExecuteAsync[T](Func`1[] options)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClient.OpenAsync(ConnectionStatusChangesHandler statusChangedHandler, ModuleClient deviceClient) in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClient.cs:line 112
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClient.CreateAndOpenDeviceClient(TransportType transport, Option`1 connectionString, ConnectionStatusChangesHandler statusChangedHandler, Option`1 productInfo) in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClient.cs:line 101
   at Microsoft.Azure.Devices.Edge.Util.Fallback.ExecuteAsync[T](Func`1[] options)<---

**Comment by varunpuranik** [comment]
This looks like a connectivity/config issue. Can you provide us the logs for iotedged? You can do $>journalctl -u iotedge. 

Also this issue is not related to the C SDK, but related to iotedge. Can you open an issue on this repo instead - https://github.com/Azure/iotedge

**Comment by jspaith** [comment]
Thanks @varunpuranik for jumping in.  Varun is correct, Edge repo is the best to track this so I'm going to close out this item on C SDK.

**Comment by az-iot-builder-01** [comment]
@asm356, @varunpuranik, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
