### ISSUE TITLE
No network error randomly occurs when SAS renewal using MQTT/websocket

### ISSUE THREAD

**Issue by alexmrtn** [Azure/azure-iot-sdk-c#790]
- **OS and version used:** Ubuntu 18.04

- **SDK version used:** lts_10_2018

# Description of the issue:
Hi, I notice that sometimes during the re-connection of the SDK (during the SAS token renewal) a "No network" status (`IOTHUB_CLIENT_CONNECTION_NO_NETWORK`) is reported. This seems to be triggered by an error is the websocket as you can see in the log (`12:44:36.572`) 

I'm running the device behind a proxy, and using the MQTT/WS protocol.

In order to quickly reproduce this the issue, I changed the default SAS token lifetime from one hour to ten minutes.

# Console log of the issue:
```
[12:44:26.522][INFO ]{azure_tests_connectionStatus.c::} Device disconnected.
[12:44:26.522][INFO ]{azure_tests_connectionStatus.c::} Connection reason : Expired SAS token.
[12:44:27.477][DEBUG]{mqtt_client.c:270}                -> 13:44:27 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: XXXXX.azure-devices.net/DDDDD/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.2.9%20(native%3b%20Linux%3b%20x86_64) | PWD: XXXX | CLEAN: 0
[12:44:27.628][DEBUG]{mqtt_client.c:297}                <- 13:44:27 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
[12:44:27.628][INFO ]{azure_tests_connectionStatus.c::} Device Connected.
[12:44:27.630][DEBUG]{mqtt_client.c:270}                -> 13:44:27 SUBSCRIBE | PACKET_ID: 222 | TOPIC_NAME: devices/DDDDD/messages/devicebound/# | QOS: 1 | TOPIC_NAME: $iothub/twin/res/# | QOS: 0 | TOPIC_NAME: $iothub/twin/PATCH/properties/desired/# | QOS: 0 | TOPIC_NAME: $iothub/methods/POST/# | QOS: 0
[12:44:27.813][DEBUG]{mqtt_client.c:297}                <- 13:44:27 SUBACK | PACKET_ID: 222 | RETURN_CODE: 1 | RETURN_CODE: 0 | RETURN_CODE: 0 | RETURN_CODE: 0
[12:44:27.815][DEBUG]{mqtt_client.c:270}                -> 13:44:27 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/GET/?$rid=223
[12:44:28.006][DEBUG]{mqtt_client.c:297}                <- 13:44:28 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/res/200/?$rid=223 | PAYLOAD_LEN: 1228
[12:44:35.462][DEBUG]{mqtt_client.c:270}                -> 13:44:35 DISCONNECT
[12:44:35.512][INFO ]{azure_tests_connectionStatus.c::} Device disconnected.
[12:44:35.512][INFO ]{azure_tests_connectionStatus.c::} Connection reason : Expired SAS token.
[12:44:36.449][DEBUG]{mqtt_client.c:270}                -> 13:44:36 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: XXXXX.azure-devices.net/DDDDD/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.2.9%20(native%3b%20Linux%3b%20x86_64) | PWD: XXXX | CLEAN: 0
[12:44:36.572][ERROR]{wsio.c:451}                       on_underlying_ws_error called with error code 3
[12:44:36.572][INFO ]{azure_tests_connectionStatus.c::} Device disconnected.
[12:44:36.572][INFO ]{azure_tests_connectionStatus.c::} Connection reason : No network.
[12:44:37.405][DEBUG]{mqtt_client.c:270}                -> 13:44:37 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: XXXXX.azure-devices.net/DDDDD/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.2.9%20(native%3b%20Linux%3b%20x86_64) | PWD: XXXX | CLEAN: 0
[12:44:37.601][DEBUG]{mqtt_client.c:297}                <- 13:44:37 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
[12:44:37.601][INFO ]{azure_tests_connectionStatus.c::} Device Connected.
[12:44:37.603][DEBUG]{mqtt_client.c:270}                -> 13:44:37 SUBSCRIBE | PACKET_ID: 224 | TOPIC_NAME: devices/DDDDD/messages/devicebound/# | QOS: 1 | TOPIC_NAME: $iothub/twin/res/# | QOS: 0 | TOPIC_NAME: $iothub/twin/PATCH/properties/desired/# | QOS: 0 | TOPIC_NAME: $iothub/methods/POST/# | QOS: 0
[12:44:37.781][DEBUG]{mqtt_client.c:297}                <- 13:44:37 SUBACK | PACKET_ID: 224 | RETURN_CODE: 1 | RETURN_CODE: 0 | RETURN_CODE: 0 | RETURN_CODE: 0
[12:44:37.783][DEBUG]{mqtt_client.c:270}                -> 13:44:37 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/GET/?$rid=225
[12:44:37.975][DEBUG]{mqtt_client.c:297}                <- 13:44:37 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/res/200/?$rid=225 | PAYLOAD_LEN: 1228
[12:44:45.468][DEBUG]{mqtt_client.c:270}                -> 13:44:45 DISCONNECT
[12:44:45.523][INFO ]{azure_tests_connectionStatus.c::} Device disconnected.
[12:44:45.523][INFO ]{azure_tests_connectionStatus.c::} Connection reason : Expired SAS token.
[12:44:46.314][DEBUG]{mqtt_client.c:270}                -> 13:44:46 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: XXXXX.azure-devices.net/DDDDD/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.2.9%20(native%3b%20Linux%3b%20x86_64) | PWD: XXXX | CLEAN: 0
[12:44:46.484][DEBUG]{mqtt_client.c:297}                <- 13:44:46 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
[12:44:46.484][INFO ]{azure_tests_connectionStatus.c::} Device Connected.

```

Any idea regarding this error ? Not sure if it is related to web-socket management or SAS renewal.

Regards,
Alexis

**Comment by alexmrtn** [comment]
Hi @jebrando , thanks for the quick reply! 

My device (Linux laptop) is actually on a corporate proxy, and I must go through this proxy to reach the internet. The device is not loosing the connection and no other disruption is happening AFAIK.

Here the backtrace of the issue:
```
#0  on_underlying_ws_error (context=0x7fffec020020, ws_error=WS_ERROR_UNDERLYING_IO_ERROR) at azure-iot-sdk-c/c-utility/src/wsio.c:451
#1  0x00007ffff7b585e8 in indicate_ws_error (uws_client=0x7fffec00a0c0, error_code=WS_ERROR_UNDERLYING_IO_ERROR) at azure-iot-sdk-c/c-utility/src/uws_client.c:596
#2  0x00007ffff7b5c007 in on_underlying_io_error (context=0x7fffec00a0c0) at azure-iot-sdk-c/c-utility/src/uws_client.c:1630
#3  0x00007ffff7b4ec6f in indicate_error (tls_io_instance=0x7fffec01ba70) at azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c:596
#4  0x00007ffff7b4f6df in on_underlying_io_error (context=0x7fffec01ba70) at azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c:781
#5  0x00007ffff7b3d3f6 in indicate_error (socket_io_instance=0x7fffec009330) at azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c:208
#6  0x00007ffff7b40e95 in socketio_dowork (socket_io=0x7fffec009330) at azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c:1002
#7  0x00007ffff7b2ebb9 in xio_dowork (xio=0x7fffec000bd0) at azure-iot-sdk-c/c-utility/src/xio.c:165
#8  0x00007ffff7b51b3a in tlsio_openssl_dowork (tls_io=0x7fffec01ba70) at azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c:1417
#9  0x00007ffff7b2ebb9 in xio_dowork (xio=0x7fffec000bf0) at azure-iot-sdk-c/c-utility/src/xio.c:165
#10 0x00007ffff7b5d634 in uws_client_dowork (uws_client=0x7fffec00a0c0) at azure-iot-sdk-c/c-utility/src/uws_client.c:2037
#11 0x00007ffff7b557d2 in wsio_dowork (ws_io=0x7fffec020020) at azure-iot-sdk-c/c-utility/src/wsio.c:648
#12 0x00007ffff7b2ebb9 in xio_dowork (xio=0x7fffec01f700) at azure-iot-sdk-c/c-utility/src/xio.c:165
#13 0x00007ffff7b2083c in mqtt_client_dowork (handle=0x555555795190) at azure-iot-sdk-c/umqtt/src/mqtt_client.c:1247
#14 0x00007ffff7b16f73 in IoTHubTransport_MQTT_Common_DoWork (handle=0x555555794f40, iotHubClientHandle=0x555555794d10) at azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c:2974
#15 0x00007ffff7b0a259 in IoTHubTransportMqtt_WS_DoWork (handle=0x555555794f40, iotHubClientHandle=0x555555794d10) at azure-iot-sdk-c/iothub_client/src/iothubtransportmqtt_websockets.c:165
#16 0x00007ffff7af4ba8 in IoTHubClientCore_LL_DoWork (iotHubClientHandle=0x555555794d10) at azure-iot-sdk-c/iothub_client/src/iothub_client_core_ll.c:1641
#17 0x00007ffff7ae73a2 in ScheduleWork_Thread (threadArgument=0x555555794810) at azure-iot-sdk-c/iothub_client/src/iothub_client_core.c:718
#18 0x00007ffff7b41d49 in ThreadWrapper (threadInstanceArg=0x555555794ad0) at azure-iot-sdk-c/c-utility/adapters/threadapi_pthreads.c:34
#19 0x00007ffff6b326db in start_thread (arg=0x7ffff145b700) at pthread_create.c:463
#20 0x00007ffff77cc88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

From line 6, we can see that the error call is due to the `recv` call in `socketio_dowork` function returns `0` and triggering the call of `indicate_error` at socketio_berkeley.c:1002.

Do you think the problem may comes from the proxy server resetting the TCP connection ?

**Comment by jebrando** [comment]
@alexmrtn I believe you hit the nail on the head.  When Berkeley returns a 0 on recv it usually means that the endpoint has disconnected the socket.  I'm guessing that the proxy has disconnect the connection.  I will talk to our web socket guy to see if there is something that can be done about this.  He is on a different team, so it may take a while to get a reply so hang tight and we'll see what we can do.

**Comment by alexmrtn** [comment]
@jebrando thanks for the feedback! Let me know if you need any other details to give to your web socket guy.

**Comment by alexmrtn** [comment]
Hi @jebrando, thanks for the update, I tested with the latest SDK and it seems that this error is no longer present! 

Two more questions:
- Do you know if the changes you made may also fix a bug where at reconnect the SDK could raise a DEVICE_DISABLED status?
- Does this fix will be included on the current lts_10_2018?

**Comment by jebrando** [comment]
This fix is not currently in the lts_10_2018.  We will be looking to update this within the next month.

**Comment by az-iot-builder-01** [comment]
@jebrando, @alexmrtn, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by alexmrtn** [comment]
Hi @jebrando 
Is it still planned to integrate the fix for this issue to the lts_10_2018 branch, or will it be available only for new releases of the SDK? We currently using the lts_10_2018 and I need to know if we have to move to the newer lts_01_2019 branch to get this fix. Thanks!
